ALTER TABLE BALANCEE ADD(
    CONSTRAINT subsc_id_fk FOREIGN KEY (SUBSC_ID) REFERENCES SUBSCRIBER(SUBSC_ID) ON DELETE CASCADE,
    CONSTRAINT package_id_fk FOREIGN KEY (PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID) ON DELETE CASCADE
);

ALTER TABLE PACKAGE_LIST ADD (
    CONSTRAINT packlist_id_fk FOREIGN KEY(PACKAGE_ID) REFERENCES PACKAGE(PACKAGE_ID) ON DELETE CASCADE
);

